### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by joyheron**
This updates a lot of dependencies. Updating fractal was the main goal
here.

Also updated the README, since the fractal config has been
`fractal.config.js` since 1.3.0

NOTE: I'm quite wary of the changes to the eslint config that occured when I ran `ncu -u`. Eslint likes to break things.

### CODE REVIEW

**Comment by joyheron** [comment]
Also note: I'm not sure how to best test this out before merging. 

So far, I've tested this out in a small dummy complate project, but haven't tested out the update in a huge project that uses complate-fractal. I will try to do that soon, but it might be worthwhile to wait to merge this until that has succeeded without issue.

**Comment by joyheron** [comment]
I really don't understand why the checks in Travis CI failed.

**Comment by joyheron** [comment]
Also: I've tested the upgrade in our big pattern library now, and it seems to work as expected.
The only issue that I ran into was with a custom fractal plugin, since the package "@frctl/fractal/src/web/server" was moved to "@frctl/web/src/server" in fractal 1.4.0

**Comment by FND** [comment]
It looks like Travis is red due to [optional `catch` binding](https://2ality.com/2017/08/optional-catch-binding.html); `.travis.yml` still uses Node v8, which is ancient.

Note that Travis is problematic anyway though, so automated releases might soon stop working.

Other than that, this seems good. Please note the [instructions for automated releases](https://github.com/complate/complate-fractal#release) though.

**Comment by joyheron** [comment]
Fractal has released a patch version since I made this PR, so I went ahead and updated the dependencies yet again (and tested this branch in my application). I'm going to merge this and make a release, and hope that travis manages to complete the automated release.

**Pull request merged**
